## 기초4_문제

In [2]:
import pandas as pd
import numpy as np

In [3]:
'''
seaborn의 타이타닉 데이터를 불러오자
'''

import seaborn as sns
df = sns.load_dataset('titanic')


In [4]:
'''
실습을 위에 데이터 소실 만들기
변경 없이 실행 시켜주시면 됩니다.
'''
df.loc[1, 'pclass'] = '?'

In [5]:
'''
데이터구조 확인 (기계적으로 확인하자)
'''


'\n데이터구조 확인 (기계적으로 확인하자)\n'

In [6]:
'''
pclass 열의 자료형 확인 _문자열(object)
df['열'].unique() 활용
'''


"\npclass 열의 자료형 확인 _문자열(object)\ndf['열'].unique() 활용\n"

In [7]:
df['pclass'].unique()

array([3, '?', 1, 2], dtype=object)

In [8]:
'''
pclass의 목록 확인
'''


'\npclass의 목록 확인\n'

In [9]:
df['pclass'].value_counts()

3    491
1    215
2    184
?      1
Name: pclass, dtype: int64

In [10]:
'''
pclass열의 누락 데이터('?') 삭제 후에 문자열을 정수형으로 변경
'''

df['pclass'].replace('?', np.nan, inplace=True)
df.dropna(subset=['pclass'], axis=0, inplace=True)
df['pclass'] = df['pclass'].astype('int')

In [11]:
'''
pclass 열의 자료형 확인 _int
'''


'\npclass 열의 자료형 확인 _int\n'

In [12]:
df['pclass'].dtypes

dtype('int32')

In [13]:
'''
df['열'].unique() 를 활용하여
pclass 열의 고유값 확인
'''


"\ndf['열'].unique() 를 활용하여\npclass 열의 고유값 확인\n"

In [14]:
df['pclass'].unique()

array([3, 1, 2])

In [15]:
'''
정수형 데이터를 문자형 데이터로 변환 
1을 1등급으로 변경
2를 2등급으로 변경
3을 3등급으로 변경
'''


'\n정수형 데이터를 문자형 데이터로 변환 \n1을 1등급으로 변경\n2를 2등급으로 변경\n3을 3등급으로 변경\n'

In [16]:
convert_dict = {
    1: '1등급',
    2: '2등급',
    3: '3등급',
}
df['pclass'].replace(convert_dict, inplace=True)
df['pclass'].unique()

array(['3등급', '1등급', '2등급'], dtype=object)

In [17]:
'''
pclass 열의 자료형 확인 _object
'''


'\npclass 열의 자료형 확인 _object\n'

In [18]:
print(df['pclass'].dtypes)

object


In [19]:
'''
origin 열의 문자열 자료형을 범주형으로 변환
'''


'\norigin 열의 문자열 자료형을 범주형으로 변환\n'

In [20]:
df['pclass'] = df['pclass'].astype('category')
print(df['pclass'].dtypes)

category


In [21]:
'''
origin 열의 범주형을 문자열로 다시 변환
'''


'\norigin 열의 범주형을 문자열로 다시 변환\n'

In [22]:
df['pclass'] = df['pclass'].astype('str')
print(df['pclass'].dtypes)

object


In [23]:
'''
fare열을 np.histogram 함수로 3개의 bin으로 나누는 경계 값의 리스트 구하기

'''

'\nfare열을 np.histogram 함수로 3개의 bin으로 나누는 경계 값의 리스트 구하기\n\n'

In [24]:
count, bin_boundary = np.histogram(df['fare'], bins=3)
print(count)
print(bin_boundary)

[870  17   3]
[  0.     170.7764 341.5528 512.3292]


In [25]:
'''
위에서 구한 세가지의 그룹을 ['하', '중', '상']로 변경해 보자
'''
bin_names = ['하', '중', '상']
df['fare_bin'] = pd.cut(df['fare'],
                       bins=bin_boundary,
                       labels=bin_names,
                       include_lowest=True)


In [26]:
'''위의 변경값 확인'''


'위의 변경값 확인'

In [27]:
df[['fare', 'fare_bin']]

fare fare_bin
0     7.2500        하
2     7.9250        하
3    53.1000        하
4     8.0500        하
5     8.4583        하
..       ...      ...
886  13.0000        하
887  30.0000        하
888  23.4500        하
889  30.0000        하
890   7.7500        하

[890 rows x 2 columns]

In [28]:
'''
fare_bin 열의 범주형 데이터를 더미 변수로 변환
'''


'\nfare_bin 열의 범주형 데이터를 더미 변수로 변환\n'

In [29]:
fare_dummies = pd.get_dummies(df['fare_bin'])
print(fare_dummies.head(15))

    하  중  상
0   1  0  0
2   1  0  0
3   1  0  0
4   1  0  0
5   1  0  0
6   1  0  0
7   1  0  0
8   1  0  0
9   1  0  0
10  1  0  0
11  1  0  0
12  1  0  0
13  1  0  0
14  1  0  0
15  1  0  0
