# week 9

* 기본적인 변수들

In [5]:
# list
a = list(range(1, 6))  # [1, 2, 3, 4, 5]
a.append(6)            # [1, 2, 3, 4, 5, 6]
a.remove(1)            # [2, 3, 4, 5, 6]

print('리스트 내 요소의 총 합 :', sum(a))
print('리스트의 요소 개수 :', len(a))

리스트 내 요소의 총 합 : 20
리스트의 요소 개수 : 5


# week 10

* 딕셔너리, 집합

In [8]:
# Dictionary
b1 = {'a': 10, 'b': 20, 'c': 30}

print(b1.keys())
print(b1.values())

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])


In [9]:
# Set
b2 = {1, 2, 3}
b3 = {2, 3, 4}

b3.add(5)            # b3 = {2, 3, 4, 5}
b3.remove(5)         # b3 = {2, 3, 4}

print(b2 & b3)
print(b2 | b3)

{2, 3}
{1, 2, 3, 4}


# week 11

* numpy에 관한 내용
    * numpy array는 요소끼리의 사칙연산이 용이함.
    * list는 요소끼리의 연산을 하려면 for문으로 요소를 꺼내서 연산해야하므로 귀찮음.

In [11]:
import numpy as np

In [15]:
# numpy array
c = np.array([10, 20, 30, 40, 50])

# operate
print(c + c)
print(c - c)
print(c * c)
print(c / c)
print()

# method
print(np.sum(c))
print(np.mean(c))
print(np.max(c))
print(np.min(c))
print()
print(np.round(c+0.1))      # default = 0 (소수점 X)
print(np.round(c+0.1, 1))   # 소수점 1번째 자리까지 반올림

[ 20  40  60  80 100]
[0 0 0 0 0]
[ 100  400  900 1600 2500]
[1. 1. 1. 1. 1.]

150
30.0
50
10

[10. 20. 30. 40. 50.]
[10.1 20.1 30.1 40.1 50.1]


In [17]:
# array 생성
c1 = np.arange(6)
c2 = np.zeros(6)
c3 = np.ones(6)

print(c1)
print(c2)
print(c3)

[0 1 2 3 4 5]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [19]:
# 2차원 배열
print(c1.reshape(2, 3))
print(c1.reshape(2, 3)[0, 2])


[[0 1 2]
 [3 4 5]]
2


# week 12

* pandas에 관한 내용

In [20]:
import pandas as pd

# week 13

* numpy에 관한 내용